### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by danielmtavares** [danielmtavares/android-bootcamp#1]
My app is complete, please review. /cc @codepathreview @codepath

The requested GIF's are [here](https://github.com/danielmtavares/android-bootcamp/blob/master/SimpleTodo/README.md)

**Comment by nesquena** [comment]
Just confirming, is this a last minute submission for a Zynga seat in the bootcamp?

**Comment by nesquena** [comment]
Can you reply here with your email address or email me at nathan@codepath.com?

**Comment by nesquena** [comment]
Ah I see your application now in the May applications (since Feb has already closed). We still have a seat for Zynga. 

Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program starts.

Nice job with the project, hope you found it as a helpful introduction and will be following up via email.

**Comment by danielmtavares** [comment]
Hey Nathan,

I just saw your comment. Sorry for the late reply. Yes, the project was helpful and allowed me to get an idea of the pace of the bootcamp. Thanks for reviewing it.
